site_name: supabase-realtime-client
site_url: https://anand2312.github.io/supabase-realtime-client
site_description: Documentation for supabase-realtime-client.
site_author: anand2312

theme:
  features:
    - navigation.top
  name: "material"
  palette:
    - scheme: slate
      primary: pink
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
    - scheme: default
      primary: pink
      toggle:
        icon: material/eye
        name: Switch to dark mode
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Reference:
      - Connection: reference/connection.md
      - Channel: reference/channel.md
      - Message: reference/message.md
      - Exceptions: reference/exceptions.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
            show_root_heading: true
            members_order: "source"

repo_name: anand2312/supabase-realtime-client
repo_url: https://github.com/anand2312/supabase-realtime-client

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: "#"
